# CodeDeploy가 전송된 해당 파일을 실행시키기 위한 설정 파일

version: 0.0
os: linux
files:
  - source: /                                  # source는 전달해준 파일 중 destination으로 이동시킬 대상입니다. / 인 경우 전체 파일을 지정하게 됩니다.
    destination: /home/ec2-user/app/step3/zip/ # destination는 파일을 받을 위치입니다.
    overwrite: yes

permissions:                                   # CodeDeploy에서 EC2 서버로 넘겨준 파일들을 모두 ec2-user 권한을 갖도록 한다.
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:                                         # CodeDeploy 배포 단계에서 실행할 명령어를 지정한다.
  AfterInstall:
    - location: stop.sh                        # 엔진엑스와 연결되어 있지 않은 스프링 부트를 종료
      timeout: 60                              # 스크립트 실행 60초 이상 수행되면 실패 (무한 대기할 수는 없으니 설정)
      runas: ec2-user
  ApplicationStart:
    - location: start.sh                       # 엔진엑스와 연결되어 있지 않은 Port로 새 버전의 스프링 부트를 시작
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh                      # 새 스프링 부트가 정상적으로 실행됐는지 확인
      timeout: 60
      runas: ec2-user