# CodeDeploy가 전송된 해당 파일을 실행시키기 위한 설정 파일

version: 0.0
os: linux
files:
  - source: /                                  # source는 전달해준 파일 중 destination으로 이동시킬 대상입니다. / 인 경우 전체 파일을 지정하게 됩니다.
    destination: /home/ec2-user/app/step3/zip/ # destination는 파일을 받을 위치입니다.
    overwrite: yes